-- ============================================================================
-- KEDAR PROPERTIES - SUPABASE DATABASE INITIALIZATION SCHEMA
-- Run this SQL code inside your Supabase Dashboard SQL Editor:
-- https://supabase.com/dashboard/project/_/sql/new
-- ============================================================================

-- 1. Create Properties Table
CREATE TABLE IF NOT EXISTS public.properties (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT,
  location TEXT,
  city TEXT NOT NULL,
  state TEXT,
  price NUMERIC,
  "priceDisplay" TEXT,
  area TEXT,
  bedrooms INT,
  bathrooms INT,
  status TEXT,
  description TEXT,
  features JSONB DEFAULT '[]'::jsonb,
  images JSONB DEFAULT '[]'::jsonb,
  featured BOOLEAN DEFAULT false,
  available BOOLEAN DEFAULT true,
  category TEXT NOT NULL,
  purpose TEXT DEFAULT 'BUY',
  locality TEXT,
  configuration TEXT,
  availability TEXT DEFAULT 'RERA Ready',
  "reraId" TEXT,
  coordinates TEXT,
  "featuredImage" TEXT,
  gallery JSONB DEFAULT '[]'::jsonb,
  highlights JSONB DEFAULT '[]'::jsonb,
  "isFeatured" BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) and allow public read/write for demo
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on properties" 
  ON public.properties FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update/delete on properties" 
  ON public.properties FOR ALL USING (true);

-- Enable Realtime broadcasting for properties table
ALTER PUBLICATION supabase_realtime ADD TABLE public.properties;


-- 2. Create Enquiries Table
CREATE TABLE IF NOT EXISTS public.enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  city TEXT,
  interests JSONB DEFAULT '[]'::jsonb,
  project_requirement TEXT,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.enquiries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert on enquiries" 
  ON public.enquiries FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow read on enquiries" 
  ON public.enquiries FOR SELECT USING (true);
